project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "SOS2901 Maskinlæring for samfunnsvitere"
  subtitle: "Oppgaver til hver undervisningsuke"
  author: "Torbjørn Skardhamar"
  date: today
  version: 0.1
  page-navigation: true
  chapters:
    - index.qmd
    - introduksjon.qmd
    - linear_regresjon.qmd
    - logistisk_regresjon.qmd
    - cart.qmd
    - bagging.qmd
    - randomForest.qmd
    - boosting.qmd
    - intro_fairness.qmd
    - fairness.qmd
  #  - unsupervised.qmd
    - oppgaver.qmd
    - references.qmd

  
  downloads: [pdf]


bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: false
    code-tools: true
  pdf:
    documentclass: scrreprt


# På kontormaskinen må jeg kjøre denne først: 
# Sys.setlocale(locale='no_NB.utf8')

