<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Lineær regresjon – SOS2901 Maskinlæring for samfunnsvitere</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./logistisk_regresjon.html" rel="next">
<link href="./introduksjon.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./linear_regresjon.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lineær regresjon</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">SOS2901 Maskinlæring for samfunnsvitere</a> 
        <div class="sidebar-tools-main">
    <a href="./SOS2901-Maskinlæring-for-samfunnsvitere.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduksjon</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./introduksjon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduksjon til maskinlæring</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./linear_regresjon.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lineær regresjon</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logistisk_regresjon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Logistisk regresjon</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cart.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Klassifikasjonstrær</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bagging.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Bagging</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./randomForest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Random forest</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro_fairness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">En lett introduksjon til fairness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fairness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Fairness og tuning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./boosting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Boosting</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#lese-inn-data" id="toc-lese-inn-data" class="nav-link active" data-scroll-target="#lese-inn-data"><span class="header-section-number">2.1</span> Lese inn data</a>
  <ul class="collapse">
  <li><a href="#training-og-testing-data" id="toc-training-og-testing-data" class="nav-link" data-scroll-target="#training-og-testing-data"><span class="header-section-number">2.1.1</span> Training og testing data</a></li>
  <li><a href="#enkel-lineær-regresjon-i-r" id="toc-enkel-lineær-regresjon-i-r" class="nav-link" data-scroll-target="#enkel-lineær-regresjon-i-r"><span class="header-section-number">2.1.2</span> Enkel lineær regresjon i R</a></li>
  <li><a href="#multippel-regresjon" id="toc-multippel-regresjon" class="nav-link" data-scroll-target="#multippel-regresjon"><span class="header-section-number">2.1.3</span> Multippel regresjon</a></li>
  <li><a href="#sammenligning-av-modeller-med-ulik-kompleksitet" id="toc-sammenligning-av-modeller-med-ulik-kompleksitet" class="nav-link" data-scroll-target="#sammenligning-av-modeller-med-ulik-kompleksitet"><span class="header-section-number">2.1.4</span> Sammenligning av modeller med ulik kompleksitet</a></li>
  <li><a href="#eksempel-på-overfitting" id="toc-eksempel-på-overfitting" class="nav-link" data-scroll-target="#eksempel-på-overfitting"><span class="header-section-number">2.1.5</span> Eksempel på overfitting</a></li>
  <li><a href="#predikere-for-nye-data" id="toc-predikere-for-nye-data" class="nav-link" data-scroll-target="#predikere-for-nye-data"><span class="header-section-number">2.1.6</span> Predikere for nye data</a></li>
  <li><a href="#generalized-additive-models-gam" id="toc-generalized-additive-models-gam" class="nav-link" data-scroll-target="#generalized-additive-models-gam"><span class="header-section-number">2.1.7</span> Generalized additive models (GAM)</a></li>
  <li><a href="#oppsummerende-kommentar" id="toc-oppsummerende-kommentar" class="nav-link" data-scroll-target="#oppsummerende-kommentar"><span class="header-section-number">2.1.8</span> Oppsummerende kommentar</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lineær regresjon</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>I dette kapittelt skal vi bruke følgende pakker:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="at">locale=</span><span class="st">'no_NB.utf8'</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)   <span class="co"># datahåndtering, grafikk og glimpse()</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)       <span class="co"># funksjonen skim() for å se på data</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsample)     <span class="co"># for å dele data i training og testing</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)        <span class="co"># for generaliserte additive modeller (GAM)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Lineær regresjon slik vi skal bruke det her er helt vanlig regresjon slik du har lært om i grunnleggende kurs i kvantitative metoder. Altså lineær funksjon estimert med minste kvadraters metode. Alt du har lært før gjelder også her. Forskjellen er at vi nå ikke er så interessert i å tolke <span class="math inline">\(\beta\)</span> men i den predikerte <span class="math inline">\(\hat{y}\)</span>.</p>
<section id="lese-inn-data" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="lese-inn-data"><span class="header-section-number">2.1</span> Lese inn data</h2>
<p>Vi illustrerer lineær regresjon med et empirisk eksempel. Her skal vi bruke data for norske kommuner i 2016. La oss si at vi er interessert i hvordan antall voldshendelser per 1000 innbyggere vil endre seg i en kommune. Dette kunne være relevant for langtidsplanlegging av forebygging, politibemanning, helsetjenester osv. Det kan være et område som er i stor endring slik at befolkningssammensetningen forventes å endre seg og/eller det er endrede lokale økonomiske utsikter.</p>
<p>Først leser vi inn dataene og tar en titt på variabellisten.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>kommune <span class="ot">&lt;-</span> <span class="fu">readRDS</span>( <span class="st">"data/kommunedata.rds"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(kommune)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,529
Columns: 28
$ kommune_nr             &lt;chr&gt; "0101", "0101", "0101", "0101", "0104", "0104",…
$ kommune                &lt;chr&gt; "Halden (-2019)", "Halden (-2019)", "Halden (-2…
$ year                   &lt;dbl&gt; 2015, 2016, 2017, 2018, 2015, 2016, 2017, 2018,…
$ bef_18min              &lt;int&gt; 3556, 3503, 3505, 3544, 3594, 3652, 3704, 3655,…
$ bef_18_25              &lt;int&gt; 3575, 3585, 3432, 3438, 3405, 3404, 3355, 3370,…
$ bef_26_35              &lt;int&gt; 3728, 3804, 3985, 4035, 4057, 4071, 4124, 4110,…
$ bef_totalt             &lt;int&gt; 30328, 30544, 30790, 31037, 31802, 32182, 32407…
$ menn_18_25             &lt;int&gt; 1847, 1865, 1813, 1819, 1789, 1802, 1789, 1810,…
$ menn_26_35             &lt;int&gt; 1880, 1919, 2005, 2062, 2063, 2083, 2113, 2134,…
$ menn_36_67             &lt;int&gt; 7067, 7051, 7085, 7057, 7418, 7453, 7408, 7407,…
$ menn_67plus            &lt;int&gt; 2496, 2624, 2697, 2806, 2671, 2777, 2856, 2895,…
$ menn_18min             &lt;int&gt; 1880, 1847, 1873, 1876, 1842, 1885, 1919, 1878,…
$ kvinner_18_25          &lt;int&gt; 1728, 1720, 1619, 1619, 1616, 1602, 1566, 1560,…
$ kvinner_26_35          &lt;int&gt; 1848, 1885, 1980, 1973, 1994, 1988, 2011, 1976,…
$ kvinner_36_67          &lt;int&gt; 6880, 6832, 6844, 6848, 7479, 7519, 7537, 7596,…
$ kvinner_67plus         &lt;int&gt; 3026, 3145, 3242, 3309, 3178, 3306, 3423, 3555,…
$ kvinner_18min          &lt;int&gt; 1676, 1656, 1632, 1668, 1752, 1767, 1785, 1777,…
$ inntekt_totalt_median  &lt;int&gt; 555000, 562000, 580000, 591000, 561000, 568000,…
$ inntekt_eskatt_median  &lt;int&gt; 451000, 453000, 470000, 480000, 449000, 456000,…
$ ant_husholdninger      &lt;int&gt; 13890, 14124, 14281, 14454, 15046, 15132, 15313…
$ shj_klienter           &lt;int&gt; 1183, 1137, 1099, 1128, 1155, 1129, 1152, 1137,…
$ shj_unge               &lt;int&gt; 262, 247, 248, 242, 267, 263, 238, 222, 307, 28…
$ vinningskriminalitet   &lt;dbl&gt; 19.7, 18.7, 16.5, 14.5, 24.5, 21.5, 18.0, 18.0,…
$ voldskriminalitet      &lt;dbl&gt; 11.2, 12.6, 12.3, 11.2, 7.8, 8.3, 8.7, 9.7, 6.8…
$ nark_alko_kriminalitet &lt;dbl&gt; 21.0, 21.9, 21.0, 20.3, 12.0, 10.2, 10.9, 10.1,…
$ ordenslovbrudd         &lt;dbl&gt; 18.5, 16.5, 14.9, 13.7, 8.9, 9.0, 9.1, 9.2, 8.2…
$ trafikklovbrudd        &lt;dbl&gt; 15.5, 16.3, 16.7, 19.2, 7.4, 6.3, 6.9, 8.0, 9.6…
$ andre_lovbrudd         &lt;dbl&gt; 25.5, 26.5, 26.1, 25.2, 12.1, 12.2, 11.9, 12.4,…</code></pre>
</div>
</div>
<p>En annen måte å få oversikt over dataene på er å bruke funksjonen <code>skim()</code>, som gir noe mer informasjon om fordelingen av hver enkelt variabel.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(kommune)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">kommune</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">1529</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">28</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">26</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">kommune_nr</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">561</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">kommune</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">561</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">year</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2017.17</td>
<td style="text-align: right;">1.70</td>
<td style="text-align: right;">2015.0</td>
<td style="text-align: right;">2016.0</td>
<td style="text-align: right;">2017.0</td>
<td style="text-align: right;">2018.0</td>
<td style="text-align: right;">2020.0</td>
<td style="text-align: left;">▇▃▃▁▃</td>
</tr>
<tr class="even">
<td style="text-align: left;">bef_18min</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2051.72</td>
<td style="text-align: right;">5134.84</td>
<td style="text-align: right;">82.0</td>
<td style="text-align: right;">478.0</td>
<td style="text-align: right;">843.0</td>
<td style="text-align: right;">1912.0</td>
<td style="text-align: right;">71566.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bef_18_25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2010.07</td>
<td style="text-align: right;">5876.07</td>
<td style="text-align: right;">90.0</td>
<td style="text-align: right;">423.0</td>
<td style="text-align: right;">772.0</td>
<td style="text-align: right;">1723.0</td>
<td style="text-align: right;">80730.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">bef_26_35</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2637.60</td>
<td style="text-align: right;">10179.34</td>
<td style="text-align: right;">80.0</td>
<td style="text-align: right;">466.0</td>
<td style="text-align: right;">873.0</td>
<td style="text-align: right;">2013.0</td>
<td style="text-align: right;">156988.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bef_totalt</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">17351.92</td>
<td style="text-align: right;">48195.14</td>
<td style="text-align: right;">934.0</td>
<td style="text-align: right;">4062.0</td>
<td style="text-align: right;">6952.0</td>
<td style="text-align: right;">15656.0</td>
<td style="text-align: right;">693494.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">menn_18_25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1033.97</td>
<td style="text-align: right;">2872.20</td>
<td style="text-align: right;">45.0</td>
<td style="text-align: right;">224.0</td>
<td style="text-align: right;">404.0</td>
<td style="text-align: right;">904.0</td>
<td style="text-align: right;">38847.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">menn_26_35</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1348.18</td>
<td style="text-align: right;">5122.76</td>
<td style="text-align: right;">44.0</td>
<td style="text-align: right;">240.0</td>
<td style="text-align: right;">456.0</td>
<td style="text-align: right;">1017.0</td>
<td style="text-align: right;">78059.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">menn_36_67</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3940.48</td>
<td style="text-align: right;">10521.30</td>
<td style="text-align: right;">234.0</td>
<td style="text-align: right;">939.0</td>
<td style="text-align: right;">1630.0</td>
<td style="text-align: right;">3650.0</td>
<td style="text-align: right;">150390.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">menn_67plus</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1361.18</td>
<td style="text-align: right;">3039.57</td>
<td style="text-align: right;">56.0</td>
<td style="text-align: right;">383.0</td>
<td style="text-align: right;">639.0</td>
<td style="text-align: right;">1330.0</td>
<td style="text-align: right;">42590.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">menn_18min</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1050.44</td>
<td style="text-align: right;">2618.78</td>
<td style="text-align: right;">44.0</td>
<td style="text-align: right;">244.0</td>
<td style="text-align: right;">434.0</td>
<td style="text-align: right;">974.0</td>
<td style="text-align: right;">36298.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">kvinner_18_25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">976.11</td>
<td style="text-align: right;">3006.75</td>
<td style="text-align: right;">38.0</td>
<td style="text-align: right;">201.0</td>
<td style="text-align: right;">365.0</td>
<td style="text-align: right;">813.0</td>
<td style="text-align: right;">41945.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">kvinner_26_35</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1289.42</td>
<td style="text-align: right;">5058.28</td>
<td style="text-align: right;">35.0</td>
<td style="text-align: right;">224.0</td>
<td style="text-align: right;">420.0</td>
<td style="text-align: right;">989.0</td>
<td style="text-align: right;">78929.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">kvinner_36_67</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3770.34</td>
<td style="text-align: right;">9932.02</td>
<td style="text-align: right;">200.0</td>
<td style="text-align: right;">862.0</td>
<td style="text-align: right;">1561.0</td>
<td style="text-align: right;">3487.0</td>
<td style="text-align: right;">140473.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">kvinner_67plus</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1580.52</td>
<td style="text-align: right;">3696.66</td>
<td style="text-align: right;">64.0</td>
<td style="text-align: right;">428.0</td>
<td style="text-align: right;">729.0</td>
<td style="text-align: right;">1488.0</td>
<td style="text-align: right;">50757.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">kvinner_18min</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1001.28</td>
<td style="text-align: right;">2516.27</td>
<td style="text-align: right;">38.0</td>
<td style="text-align: right;">232.0</td>
<td style="text-align: right;">405.0</td>
<td style="text-align: right;">933.0</td>
<td style="text-align: right;">35268.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">inntekt_totalt_median</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">654721.39</td>
<td style="text-align: right;">75785.29</td>
<td style="text-align: right;">463000.0</td>
<td style="text-align: right;">601000.0</td>
<td style="text-align: right;">646000.0</td>
<td style="text-align: right;">697000.0</td>
<td style="text-align: right;">898000.0</td>
<td style="text-align: left;">▁▇▇▃▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">inntekt_eskatt_median</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">519417.92</td>
<td style="text-align: right;">52786.68</td>
<td style="text-align: right;">376000.0</td>
<td style="text-align: right;">482000.0</td>
<td style="text-align: right;">514000.0</td>
<td style="text-align: right;">550000.0</td>
<td style="text-align: right;">675000.0</td>
<td style="text-align: left;">▁▆▇▃▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">ant_husholdninger</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7873.76</td>
<td style="text-align: right;">23631.34</td>
<td style="text-align: right;">426.0</td>
<td style="text-align: right;">1831.0</td>
<td style="text-align: right;">3137.0</td>
<td style="text-align: right;">6896.0</td>
<td style="text-align: right;">348864.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">shj_klienter</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">449.81</td>
<td style="text-align: right;">1383.19</td>
<td style="text-align: right;">11.0</td>
<td style="text-align: right;">98.0</td>
<td style="text-align: right;">179.0</td>
<td style="text-align: right;">376.0</td>
<td style="text-align: right;">20401.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">shj_unge</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">89.36</td>
<td style="text-align: right;">197.02</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">20.0</td>
<td style="text-align: right;">39.0</td>
<td style="text-align: right;">89.0</td>
<td style="text-align: right;">2488.0</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">vinningskriminalitet</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.19</td>
<td style="text-align: right;">7.05</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">4.8</td>
<td style="text-align: right;">7.2</td>
<td style="text-align: right;">11.5</td>
<td style="text-align: right;">91.2</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">voldskriminalitet</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5.61</td>
<td style="text-align: right;">2.28</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">3.9</td>
<td style="text-align: right;">5.2</td>
<td style="text-align: right;">6.8</td>
<td style="text-align: right;">18.8</td>
<td style="text-align: left;">▇▇▂▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nark_alko_kriminalitet</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6.91</td>
<td style="text-align: right;">4.60</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">3.9</td>
<td style="text-align: right;">5.9</td>
<td style="text-align: right;">8.9</td>
<td style="text-align: right;">55.5</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">ordenslovbrudd</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.91</td>
<td style="text-align: right;">3.23</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.1</td>
<td style="text-align: right;">5.9</td>
<td style="text-align: right;">34.9</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">trafikklovbrudd</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10.49</td>
<td style="text-align: right;">11.36</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">8.1</td>
<td style="text-align: right;">11.7</td>
<td style="text-align: right;">219.7</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">andre_lovbrudd</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.59</td>
<td style="text-align: right;">4.34</td>
<td style="text-align: right;">2.3</td>
<td style="text-align: right;">7.1</td>
<td style="text-align: right;">8.8</td>
<td style="text-align: right;">10.8</td>
<td style="text-align: right;">52.5</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="training-og-testing-data" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="training-og-testing-data"><span class="header-section-number">2.1.1</span> Training og testing data</h3>
<p>Vi starter med å dele datasettet i <em>training</em> og <em>testing</em>. Her kan vi bruke pakken ‘rsample’ og funksjonen <code>initial_split()</code> etterfulgt av funksjonene <code>training()</code> og <code>testing()</code>. Forhåndsvalget for splitten er 0.75, så dermed brukes 75% til training og resten til testing. Du kan også legge til argumentet <code>prop =</code> og sette en annen andel, f.eks. 0.7 for 70%.</p>
<p>Merk bruken av <code>set.seed()</code>. For å splitte genererer R tilfeldige tall, og <em>seed</em> styrer hvor den algoritmen starter. Når <em>seed</em> er satt vil du få nøyaktig samme resultatet som gjort her. Dette vil du trenge på eksamen for at sensor skal kunne sjekke resultatene dine, så begynn å bruke det med en gang. Tallet inni parentesen betyr ingenting<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> og bare sørger for reproduserbarhet der hvor det er tilfeldige tall involvert.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>kommune_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(kommune, <span class="at">prop =</span> .<span class="dv">7</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>kommune_train <span class="ot">&lt;-</span> <span class="fu">training</span>(kommune_split)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>kommune_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(kommune_split)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="enkel-lineær-regresjon-i-r" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="enkel-lineær-regresjon-i-r"><span class="header-section-number">2.1.2</span> Enkel lineær regresjon i R</h3>
<p>En ganske åpenbar faktor som forklarer forekomsten av vold er andel unge menn i kommunen. Rett og slett fordi dette er den demografiske gruppen som begår mest vold - og kriminalitet generelt, faktisk. Hvis befolkningssammensetningen forventes å bli yngre vil det medføre flere unge menn, og da kan vi kanskje forvente at det blir flere voldshendelser bare av den grunn? Sammenhengen mellom unge menn og voldsrate kan estimeres med helt vanlig lineær regresjon.</p>
<p>En god start på de fleste empiriske analyser er å beskrive sammenhengen med et plot. Her legger vi på en lineær regresjonslinje med <code>geom_smooth()</code> der vi presiserer lineær modell med <code>method = "lm"</code> og lar være å ta med konfidensintervallet <code>se = FALSE</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>kommune_train <span class="ot">&lt;-</span> kommune_train <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop_unge_menn =</span> (menn_18_25 <span class="sc">+</span> menn_26_35)<span class="sc">/</span>bef_totalt<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kommune_train, <span class="fu">aes</span>(<span class="at">x =</span> prop_unge_menn,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> voldskriminalitet)) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="linear_regresjon_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Lineær regresjon estimeres med <code>lm()</code> og du kan få en enkel output med bruk av <code>summary()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>est <span class="ot">&lt;-</span> <span class="fu">lm</span>(voldskriminalitet <span class="sc">~</span> prop_unge_menn, <span class="at">data =</span> kommune_train)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(est)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = voldskriminalitet ~ prop_unge_menn, data = kommune_train)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.0302 -1.5764 -0.3951  1.1826 11.3367 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     0.50954    0.63482   0.803    0.422    
prop_unge_menn  0.41329    0.05097   8.109  1.4e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.248 on 1068 degrees of freedom
Multiple R-squared:  0.05799,   Adjusted R-squared:  0.05711 
F-statistic: 65.75 on 1 and 1068 DF,  p-value: 1.395e-15</code></pre>
</div>
</div>
<p>Man kan også hente ut kun <span class="math inline">\(r^2\)</span> med følgende kode:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(est)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05799176</code></pre>
</div>
</div>
<p>For ordens skyld: I tidligere metodekurs har du kanskje lært å få ut en penere regresjonstabell med f.eks. gtsummary-pakken. (Det finnes andre pakker også som gjør tilsvarende). Hvordan output er formatert spiller ingen rolle. I denne sammenhengen har vi lite bruk for en pen regresjonstabell da <span class="math inline">\(\beta\)</span> ikke er av primær interesse.</p>
<p>Med andre ord kan voldsraten beskrives som:</p>
<p><span class="math display">\[
\operatorname{\widehat{voldskriminalitet}} = 0.51 + 0.41(\operatorname{prop\_unge\_menn})
\]</span></p>
<p>Men vi har også sett at <span class="math inline">\(r^2\)</span> er ganske lav, bare 0.058. Denne koeffisienten kalles også “coefficient of determination” og sier noe om i hvor stor grad modellen fanger opp variasjoenen i dataene. En lav <span class="math inline">\(r^2\)</span> betyr at modellen i liten grad gjør det. Vi må altså forvente at modellen vil bomme ganske kraftig i sine prediksjoner. Vi kan velge å ta modellen seriøst likevel, men ikke ha for store forventninger for prediksjonene!</p>
<p>Et annet mål på hvor godt modellen treffer er “Root mean square error”, RMSE. Dette kan skrives som:</p>
<p><span class="math display">\[ rmse = \sqrt{ \frac{ \sum{(O_i-P_i)^2} }{N} }  \]</span></p>
<p>der <span class="math inline">\(O\)</span> er de observerte verdiene og <span class="math inline">\(P\)</span> er de predikerte verdiene for observasjon <span class="math inline">\(i\)</span>. Merk at <span class="math inline">\((O_i-P_i)\)</span> er residualene. I R kan vi hente ut residualene fra regresjons-objektet med dollartegnet <code>...$res</code> etter objektnavnet. Da kan du regne ut RMSE som følger:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(est<span class="sc">$</span>res<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>rmse</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.245685</code></pre>
</div>
</div>
<p>RMSE sier altså omtrentlig hvor mye modellen i gjennomsnitt bommer på de observerte verdiene. <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Hvorvidt det er presist <em>nok</em> eller ikke vil vel strengt tatt komme an på behovet for presisjon, altså: hva man skal bruke det til.</p>
<p>For å få litt bedre tak på hva RMSE betyr kan vi se på et plot av de predikerte og observerte verdiene. Vi kan predikere vold for hver enkelt kommune basert på denne modellen, som altså er den forventede voldsraten <em>hvis modellen er sann</em>. Funksjonen <code>predict()</code> gir oss hva vi trenger.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>kom <span class="ot">&lt;-</span> kommune_train <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> <span class="fu">predict</span>(est))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Merk at koden her lagde en kopi av datasettet der vi har alle de opprinnelige variablene pluss en variabel med de predikerte verdiene. Vi kan nå sammenlignet prediksjonene med de observerte utfallene.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kom, <span class="fu">aes</span>(<span class="at">x =</span> voldskriminalitet, <span class="at">y =</span> pred)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="linear_regresjon_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Hvis prediksjonen hadde vært perfekt ville disse punktene ligget på linja, noe den jo ikke gjør. Modellen bommer altså ganske mye.</p>
<p>Hva hvis vi vil vite forventet voldsrate for en kommune for en gitt andel unge menn? Løsningen er å lage et nytt datasett med de verdiene vi er interessert i og så predikere for dette datasettet med å spesifisere <code>newdata = dt</code>. Her er et eksempel der vi ønsker å vite voldsraten hvis andelen unge menn er 15%.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dt <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">prop_unge_menn =</span> <span class="dv">15</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">predict</span>(est, <span class="at">newdata =</span> dt)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
6.708919 </code></pre>
</div>
</div>
<p>I følge modellen vil altså en kommune der 15% av populasjonen er unge menn ha en 6.709 voldshendelser per 1000 innbyggere. Fra tradisjonell statistikk vet vi jo at det er usikkerhet knyttet til dette estimatet og vi kan også ta det med i beregningen her. Vanligvis vil man estimere med et <em>konfidensintervall</em>, som gjelder hvis man estimerer et gjennomsnitt i en gruppe. Her skal vi derimot predikere for en enkelt kommune, som da har større usikkerhet enn om man estimerer for en enkelt observasjon. Dette kalles prediksjonsintervall og må spesifiseres i koden. Hvis det ikke er gitt vil R gi konfidensintervallet.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>p_ki <span class="ot">&lt;-</span> <span class="fu">predict</span>(est, <span class="at">newdata =</span> dt, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>p_ki</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 6.708919 2.288514 11.12932</code></pre>
</div>
</div>
<p>Tolkningen er ellers tilsvarende som for konfidensintervall: vi forventer med “95% sannsynlighet”<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> at voldsraten vil være mellom 2.3 og 11.1 per 1000 innbyggere.</p>
</section>
<section id="multippel-regresjon" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3" class="anchored" data-anchor-id="multippel-regresjon"><span class="header-section-number">2.1.3</span> Multippel regresjon</h3>
<p>Enkel regresjon er nettopp enkel og prediksjonen blir ikke så god. Men vi kan komplisere vesentlig ved å inkludere flere variable og bruke alle triksene man evt. har lært om multippel regresjon tidligere, primært interaksjonsledd, polynomer og transformasjoner osv. (Det er ok om du ikke har lært alt dette tidligere).</p>
<p>I R vil vi da bare legge til flere variabelnavn i formelen. Ellers er det meste likt som for enkel lineær regresjon.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>est_m <span class="ot">&lt;-</span> <span class="fu">lm</span>(voldskriminalitet <span class="sc">~</span> prop_unge_menn <span class="sc">+</span> inntekt_totalt_median <span class="sc">+</span> shj_unge <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                   ant_husholdninger ,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> kommune_train)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(est_m)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = voldskriminalitet ~ prop_unge_menn + inntekt_totalt_median + 
    shj_unge + ant_husholdninger, data = kommune_train)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.6862 -1.3599 -0.2042  1.0689 12.4822 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            7.421e+00  7.333e-01  10.121  &lt; 2e-16 ***
prop_unge_menn         4.177e-01  5.328e-02   7.840 1.09e-14 ***
inntekt_totalt_median -1.099e-05  8.539e-07 -12.871  &lt; 2e-16 ***
shj_unge               4.461e-03  1.016e-03   4.392 1.23e-05 ***
ant_husholdninger     -2.163e-05  8.361e-06  -2.587  0.00983 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.037 on 1065 degrees of freedom
Multiple R-squared:  0.2288,    Adjusted R-squared:  0.2259 
F-statistic:    79 on 4 and 1065 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Merk at <span class="math inline">\(r^2\)</span> nå har gått betraktelig opp, til ca 0.23. Gitt at vi tolker dette som i hvor stor grad vi kan <em>predikere</em> utfallet fra datasettet, så er det kanskje likevel ikke imponerende høyt: vi vil fremdeles forvente mye feil prediksjon.</p>
<p>Her er et scatterplot av observert mot forventet voldsrater:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>kom_pred <span class="ot">&lt;-</span> kommune_train <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> <span class="fu">predict</span>(est_m))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kom_pred, <span class="fu">aes</span>(<span class="at">x =</span> voldskriminalitet, <span class="at">y =</span> pred)) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="linear_regresjon_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sammenligning-av-modeller-med-ulik-kompleksitet" class="level3" data-number="2.1.4">
<h3 data-number="2.1.4" class="anchored" data-anchor-id="sammenligning-av-modeller-med-ulik-kompleksitet"><span class="header-section-number">2.1.4</span> Sammenligning av modeller med ulik kompleksitet</h3>
<p>La oss nå systematisk sammenligne flere modeller med ulik kompleksitet. Vi lager først et datasett med utvalgte variable og bruker formelen <code>voldskriminalitet ~ .</code> for å ta med alle variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>kom_s <span class="ot">&lt;-</span> kommune_train <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(kommune, kommune_nr, ordenslovbrudd,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>            nark_alko_kriminalitet, trafikklovbrudd, andre_lovbrudd,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>            prop_unge_menn))</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>full_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(voldskriminalitet <span class="sc">~</span> . , <span class="at">data =</span> kom_s)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = voldskriminalitet ~ ., data = kom_s)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.9650 -1.2333 -0.1813  0.8919 12.2114 

Coefficients: (4 not defined because of singularities)
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           -1.198e+02  9.309e+01  -1.287  0.19851    
year                   6.234e-02  4.646e-02   1.342  0.17998    
bef_18min              3.156e-03  1.839e-03   1.716  0.08637 .  
bef_18_25             -1.885e-05  1.513e-03  -0.012  0.99006    
bef_26_35              1.180e-03  1.006e-03   1.173  0.24109    
bef_totalt            -2.272e-03  7.130e-04  -3.187  0.00148 ** 
menn_18_25             3.698e-03  2.136e-03   1.731  0.08373 .  
menn_26_35            -1.481e-03  2.013e-03  -0.736  0.46197    
menn_36_67             2.710e-03  9.461e-04   2.865  0.00425 ** 
menn_67plus            1.654e-03  1.339e-03   1.236  0.21676    
menn_18min             2.461e-03  2.875e-03   0.856  0.39223    
kvinner_18_25                 NA         NA      NA       NA    
kvinner_26_35                 NA         NA      NA       NA    
kvinner_36_67         -1.269e-04  9.021e-04  -0.141  0.88816    
kvinner_67plus                NA         NA      NA       NA    
kvinner_18min                 NA         NA      NA       NA    
inntekt_totalt_median -4.693e-05  7.600e-06  -6.176 9.40e-10 ***
inntekt_eskatt_median  5.580e-05  1.108e-05   5.037 5.55e-07 ***
ant_husholdninger      1.555e-03  3.169e-04   4.908 1.07e-06 ***
shj_klienter           2.170e-03  9.967e-04   2.177  0.02968 *  
shj_unge               2.191e-03  3.054e-03   0.718  0.47322    
vinningskriminalitet   1.066e-01  1.014e-02  10.513  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.891 on 1052 degrees of freedom
Multiple R-squared:  0.343, Adjusted R-squared:  0.3324 
F-statistic:  32.3 on 17 and 1052 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math inline">\(r^2\)</span> gikk noe opp, til 0.343.</p>
</section>
<section id="eksempel-på-overfitting" class="level3" data-number="2.1.5">
<h3 data-number="2.1.5" class="anchored" data-anchor-id="eksempel-på-overfitting"><span class="header-section-number">2.1.5</span> Eksempel på overfitting</h3>
<p>Men vi kan gjøre modellen ekstra komplisert ved inkludere alle mulige interaksjonsledd. En åpenbar ulempe med dette er at hver enkelt koeffisent blir svært mye vanskeligere å tolke. Vi fokuserer derfor kun på <span class="math inline">\(r^2\)</span> og RMSE.</p>
<p>Her bygger vi fire modeller med økende kompleksitet og sammenligner RMSE for training-data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>est1 <span class="ot">&lt;-</span> est     <span class="co"># enkel modell med bare prop_unge_menn (estimert over)</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>est2 <span class="ot">&lt;-</span> est_m   <span class="co"># multippel regresjon (estimert over)</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>est3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(voldskriminalitet <span class="sc">~</span> .<span class="sc">^</span><span class="dv">2</span>, <span class="at">data =</span> kom_s)    <span class="co"># alle 2-veis interaksjoner</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>est4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(voldskriminalitet <span class="sc">~</span> .<span class="sc">^</span><span class="dv">3</span>, <span class="at">data =</span> kom_s)    <span class="co"># alle 3-veis interaksjoner</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>RMSE for training-data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(est1<span class="sc">$</span>res<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.245685</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(est2<span class="sc">$</span>res<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.031873</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(est3<span class="sc">$</span>res<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.598957</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(est4<span class="sc">$</span>res<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9963221</code></pre>
</div>
</div>
<p>For training-data ser vi altså at RMSE synker for hver modell. Mer kompleksitet gir tilsynelatende bedre tilpassning. Men hva skjer med testing-data?</p>
</section>
<section id="predikere-for-nye-data" class="level3" data-number="2.1.6">
<h3 data-number="2.1.6" class="anchored" data-anchor-id="predikere-for-nye-data"><span class="header-section-number">2.1.6</span> Predikere for nye data</h3>
<p>Nå har vi bare sett på hvordan prediksjonen fungerer på training-datasettet. Vi må sjekke med testing-datasettet. Det lagde vi i begynnelsen, så nå henter vi det frem. I <code>predict()</code> må vi nå angi <code>newdata =</code>. Vi predikerer fra alle fire modellene samtidig og regner ut RMSE for testing-data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>kommune_test <span class="ot">&lt;-</span> kommune_test <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop_unge_menn =</span> (menn_18_25 <span class="sc">+</span> menn_26_35)<span class="sc">/</span>bef_totalt<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>kommune_pred <span class="ot">&lt;-</span> kommune_test <span class="sc">%&gt;%</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred1 =</span> <span class="fu">predict</span>(est1, <span class="at">newdata =</span> .),</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">pred2 =</span> <span class="fu">predict</span>(est2, <span class="at">newdata =</span> .),</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">pred3 =</span> <span class="fu">predict</span>(est3, <span class="at">newdata =</span> .),</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">pred4 =</span> <span class="fu">predict</span>(est4, <span class="at">newdata =</span> .))</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>rmse_test <span class="ot">&lt;-</span> kommune_pred <span class="sc">%&gt;%</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">res1 =</span> pred1 <span class="sc">-</span> voldskriminalitet,</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">res2 =</span> pred2 <span class="sc">-</span> voldskriminalitet,</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">res3 =</span> pred3 <span class="sc">-</span> voldskriminalitet,</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">res4 =</span> pred4 <span class="sc">-</span> voldskriminalitet) <span class="sc">%&gt;%</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">RMSE_enkel =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(res1<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_multippel =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(res2<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_2veis =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(res3<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_3veis =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(res4<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>rmse_test</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  RMSE_enkel RMSE_multippel RMSE_2veis RMSE_3veis
1   2.147951       1.876014   23.41166   7109.869</code></pre>
</div>
</div>
<p>Her ser vi at de mest kompliserte modellene gir <em>dårligere</em> prediksjon på nye data! La oss også plotte predikert mot observert for den mest kompliserte modellen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kommune_pred, <span class="fu">aes</span>(<span class="at">x =</span> voldskriminalitet, <span class="at">y =</span> pred4)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="linear_regresjon_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ser dette rart ut? Det er noen observasjoner som har predikert skyhøy voldsrate! Disse prediksjonene bommer voldsomt.</p>
<p>Sammenlignet er den enklere multippelregresjonsmodellen vesentlig bedre på nye data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kommune_pred, <span class="fu">aes</span>(<span class="at">x =</span> voldskriminalitet, <span class="at">y =</span> pred2)) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="linear_regresjon_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Dette er en ganske ekstrem variant av <em>overfitting</em>. Ved å formulere en veldig komplisert modell som passer veldig godt til training-dataene kan vi ende opp med en modell som passer veldig, veldig dårlig til nye data. Hvis man skulle utforme f.eks. politikktiltak på grunnlag av en slik prediksjon vil det kunne gå riktig så dårlig.</p>
<p>Det er altså slik at en enklere modell kan passe til <em>nye</em> data langt bedre enn en veldig komplisert modell. Grunnen er overfitting: modellen fanger opp vel så mye tilfeldig støy som det underliggende mønsteret. Støyen vil jo være annerledes i de nye dataene.</p>
</section>
<section id="generalized-additive-models-gam" class="level3" data-number="2.1.7">
<h3 data-number="2.1.7" class="anchored" data-anchor-id="generalized-additive-models-gam"><span class="header-section-number">2.1.7</span> Generalized additive models (GAM)</h3>
<p>Generaliserte additive modeller er i utgangspunktet som lineær regresjon, men inkluderer en eller flere <em>smoothing</em>-parametre. Disse smoothing-parametrene “lærer” funksjonsformen fra dataene i stedet for å anta en lineær sammenheng. Funksjonen <code>gam()</code> fra pakken <code>mgcv</code> brukes for dette, og <code>s()</code> rundt en variabel angir at den skal ha en fleksibel form.</p>
<p>Her er et eksempel der vi bruker GAM med noen utvalgte variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>gam_mod <span class="ot">&lt;-</span> <span class="fu">gam</span>(voldskriminalitet <span class="sc">~</span> <span class="fu">s</span>(prop_unge_menn) <span class="sc">+</span> <span class="fu">s</span>(inntekt_totalt_median) <span class="sc">+</span> <span class="fu">s</span>(shj_unge),</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> kommune_train)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gam_mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Family: gaussian 
Link function: identity 

Formula:
voldskriminalitet ~ s(prop_unge_menn) + s(inntekt_totalt_median) + 
    s(shj_unge)

Parametric coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.62673    0.05937   94.77   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Approximate significance of smooth terms:
                           edf Ref.df     F p-value    
s(prop_unge_menn)        1.000  1.000 68.21  &lt;2e-16 ***
s(inntekt_totalt_median) 5.197  6.339 37.48  &lt;2e-16 ***
s(shj_unge)              4.478  5.462 22.78  &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

R-sq.(adj) =  0.296   Deviance explained = 30.3%
GCV = 3.8136  Scale est. = 3.772     n = 1070</code></pre>
</div>
</div>
<p>Vi kan plotte de estimerte smoothing-funksjonene for å se hvordan sammenhengen ser ut:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gam_mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="linear_regresjon_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="linear_regresjon_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="linear_regresjon_files/figure-html/unnamed-chunk-23-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Merk at <code>s()</code> tilpasser en fleksibel kurve til dataene. Fordelen med GAM er at vi ikke trenger å anta en lineær sammenheng. Ulempen er at det er vanskeligere å tolke koeffisientene direkte, men for <em>prediksjon</em> er dette ofte ikke et problem.</p>
</section>
<section id="oppsummerende-kommentar" class="level3" data-number="2.1.8">
<h3 data-number="2.1.8" class="anchored" data-anchor-id="oppsummerende-kommentar"><span class="header-section-number">2.1.8</span> Oppsummerende kommentar</h3>
<p>Dette gjelder generelt: mer komplisert regresjonsmodell vil gi tilsynelatende bedre tilpassning til data enten man måler med <span class="math inline">\(r^2\)</span> eller RMSE. Man kan riktignok bruke mål på tilpassning som justerer for antall parametre etc (f.eks. justert <span class="math inline">\(r^2\)</span>, AIC eller BIC), som kanskje kan bedre dette noe, men det vil ofte lede til overfitting likevel.</p>
<p>Det er derfor veldig viktig å teste modellen mot <em>nye</em> data. I praksis testing-dataene man lagde til å begynne med.</p>
<p>I resten av kurset skal vi unngå å bruke latterlige kompliserte modeller som ble demonstrert ovenfor. Man kan godt bruke interaksjonsledd, polynomer, splines og andre fancy ting. Men med måte.</p>


<!-- -->

</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Bortsett fra for dem som mener det er svaret på “the Ultimate Question of Life, the Universe, and Everything”<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Denne formuleringen er ganske omtrentlig. RMSE er egentlig kvadratroten av gjennomsnittet til de kvadrerte residualene, som er noe litt annet enn gjennomsnittet av de absolutte verdiene av residualene. Det gir bl.a. litt mer vekt til store residualer enn et vanlig gjennomsnitt.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Dette er en omtrentelig formulering. Alle sannsynligheter gjelder i det lange løp: altså hvis man gjør undersøkelsen veldig mange ganger.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./introduksjon.html" class="pagination-link" aria-label="Introduksjon til maskinlæring">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduksjon til maskinlæring</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./logistisk_regresjon.html" class="pagination-link" aria-label="Logistisk regresjon">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Logistisk regresjon</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb40" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Lineær regresjon</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>I dette kapittelt skal vi bruke følgende pakker:</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: true</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="fu">invisible</span>(<span class="fu">Sys.setlocale</span>(<span class="at">locale=</span><span class="st">'no_NB.utf8'</span>))</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)   <span class="co"># datahåndtering, grafikk og glimpse()</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)       <span class="co"># funksjonen skim() for å se på data</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsample)     <span class="co"># for å dele data i training og testing</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mgcv)        <span class="co"># for generaliserte additive modeller (GAM)</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>Lineær regresjon slik vi skal bruke det her er helt vanlig regresjon slik du har lært om i grunnleggende kurs i kvantitative metoder. Altså lineær funksjon estimert med minste kvadraters metode. Alt du har lært før gjelder også her. Forskjellen er at vi nå ikke er så interessert i å tolke $\beta$ men i den predikerte $\hat{y}$.</span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a><span class="fu">## Lese inn data</span></span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>Vi illustrerer lineær regresjon med et empirisk eksempel. Her skal vi bruke data for norske kommuner i 2016. La oss si at vi er interessert i hvordan antall voldshendelser per 1000 innbyggere vil endre seg i en kommune. Dette kunne være relevant for langtidsplanlegging av forebygging, politibemanning, helsetjenester osv. Det kan være et område som er i stor endring slik at befolkningssammensetningen forventes å endre seg og/eller det er endrede lokale økonomiske utsikter.</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>Først leser vi inn dataene og tar en titt på variabellisten.</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a>kommune <span class="ot">&lt;-</span> <span class="fu">readRDS</span>( <span class="st">"data/kommunedata.rds"</span>)</span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(kommune)</span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a>En annen måte å få oversikt over dataene på er å bruke funksjonen <span class="in">`skim()`</span>, som gir noe mer informasjon om fordelingen av hver enkelt variabel.</span>
<span id="cb40-40"><a href="#cb40-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-43"><a href="#cb40-43" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-44"><a href="#cb40-44" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(kommune)</span>
<span id="cb40-45"><a href="#cb40-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-46"><a href="#cb40-46" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-47"><a href="#cb40-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-48"><a href="#cb40-48" aria-hidden="true" tabindex="-1"></a><span class="fu">### Training og testing data</span></span>
<span id="cb40-49"><a href="#cb40-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-50"><a href="#cb40-50" aria-hidden="true" tabindex="-1"></a>Vi starter med å dele datasettet i *training* og *testing*. Her kan vi bruke pakken 'rsample' og funksjonen <span class="in">`initial_split()`</span> etterfulgt av funksjonene <span class="in">`training()`</span> og <span class="in">`testing()`</span>. Forhåndsvalget for splitten er 0.75, så dermed brukes  75% til training og resten til testing. Du kan også legge til argumentet <span class="in">`prop = `</span> og sette en annen andel, f.eks. 0.7 for 70%.</span>
<span id="cb40-51"><a href="#cb40-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-52"><a href="#cb40-52" aria-hidden="true" tabindex="-1"></a>Merk bruken av <span class="in">`set.seed()`</span>. For å splitte genererer R tilfeldige tall, og *seed* styrer hvor den algoritmen starter. Når *seed* er satt vil du få nøyaktig samme resultatet som gjort her. Dette vil du trenge på eksamen for at sensor skal kunne sjekke resultatene dine, så begynn å bruke det med en gang. Tallet inni parentesen betyr ingenting<span class="ot">[^linear_regresjon-1]</span> og bare sørger for reproduserbarhet der hvor det er tilfeldige tall involvert.</span>
<span id="cb40-53"><a href="#cb40-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-54"><a href="#cb40-54" aria-hidden="true" tabindex="-1"></a><span class="ot">[^linear_regresjon-1]: </span>Bortsett fra for dem som mener det er svaret på "the Ultimate Question of Life, the Universe, and Everything"</span>
<span id="cb40-55"><a href="#cb40-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-58"><a href="#cb40-58" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-59"><a href="#cb40-59" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb40-60"><a href="#cb40-60" aria-hidden="true" tabindex="-1"></a>kommune_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(kommune, <span class="at">prop =</span> .<span class="dv">7</span>)</span>
<span id="cb40-61"><a href="#cb40-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-62"><a href="#cb40-62" aria-hidden="true" tabindex="-1"></a>kommune_train <span class="ot">&lt;-</span> <span class="fu">training</span>(kommune_split)</span>
<span id="cb40-63"><a href="#cb40-63" aria-hidden="true" tabindex="-1"></a>kommune_test <span class="ot">&lt;-</span> <span class="fu">testing</span>(kommune_split)</span>
<span id="cb40-64"><a href="#cb40-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-65"><a href="#cb40-65" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-66"><a href="#cb40-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-67"><a href="#cb40-67" aria-hidden="true" tabindex="-1"></a><span class="fu">### Enkel lineær regresjon i R</span></span>
<span id="cb40-68"><a href="#cb40-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-69"><a href="#cb40-69" aria-hidden="true" tabindex="-1"></a>En ganske åpenbar faktor som forklarer forekomsten av vold er andel unge menn i kommunen. Rett og slett fordi dette er den demografiske gruppen som begår mest vold - og kriminalitet generelt, faktisk. Hvis befolkningssammensetningen forventes å bli yngre vil det medføre flere unge menn, og da kan vi kanskje forvente at det blir flere voldshendelser bare av den grunn? Sammenhengen mellom unge menn og voldsrate kan estimeres med helt vanlig lineær regresjon.</span>
<span id="cb40-70"><a href="#cb40-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-71"><a href="#cb40-71" aria-hidden="true" tabindex="-1"></a>En god start på de fleste empiriske analyser er å beskrive sammenhengen med et plot. Her legger vi på en lineær regresjonslinje med <span class="in">`geom_smooth()`</span> der vi presiserer lineær modell med <span class="in">`method = "lm"`</span> og lar være å ta med konfidensintervallet <span class="in">`se = FALSE`</span>.</span>
<span id="cb40-72"><a href="#cb40-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-75"><a href="#cb40-75" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-76"><a href="#cb40-76" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb40-77"><a href="#cb40-77" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb40-78"><a href="#cb40-78" aria-hidden="true" tabindex="-1"></a>kommune_train <span class="ot">&lt;-</span> kommune_train <span class="sc">%&gt;%</span></span>
<span id="cb40-79"><a href="#cb40-79" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop_unge_menn =</span> (menn_18_25 <span class="sc">+</span> menn_26_35)<span class="sc">/</span>bef_totalt<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb40-80"><a href="#cb40-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-81"><a href="#cb40-81" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kommune_train, <span class="fu">aes</span>(<span class="at">x =</span> prop_unge_menn,</span>
<span id="cb40-82"><a href="#cb40-82" aria-hidden="true" tabindex="-1"></a>                     <span class="at">y =</span> voldskriminalitet)) <span class="sc">+</span></span>
<span id="cb40-83"><a href="#cb40-83" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb40-84"><a href="#cb40-84" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb40-85"><a href="#cb40-85" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-86"><a href="#cb40-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-87"><a href="#cb40-87" aria-hidden="true" tabindex="-1"></a>Lineær regresjon estimeres med <span class="in">`lm()`</span> og du kan få en enkel output med bruk av <span class="in">`summary()`</span>.</span>
<span id="cb40-88"><a href="#cb40-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-91"><a href="#cb40-91" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-92"><a href="#cb40-92" aria-hidden="true" tabindex="-1"></a>est <span class="ot">&lt;-</span> <span class="fu">lm</span>(voldskriminalitet <span class="sc">~</span> prop_unge_menn, <span class="at">data =</span> kommune_train)</span>
<span id="cb40-93"><a href="#cb40-93" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(est)</span>
<span id="cb40-94"><a href="#cb40-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-95"><a href="#cb40-95" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-96"><a href="#cb40-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-97"><a href="#cb40-97" aria-hidden="true" tabindex="-1"></a>Man kan også hente ut kun $r^2$ med følgende kode:</span>
<span id="cb40-98"><a href="#cb40-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-101"><a href="#cb40-101" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-102"><a href="#cb40-102" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb40-103"><a href="#cb40-103" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(est)<span class="sc">$</span>r.squared</span>
<span id="cb40-104"><a href="#cb40-104" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-105"><a href="#cb40-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-106"><a href="#cb40-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-107"><a href="#cb40-107" aria-hidden="true" tabindex="-1"></a>For ordens skyld: I tidligere metodekurs har du kanskje lært å få ut en penere regresjonstabell med f.eks. gtsummary-pakken. (Det finnes andre pakker også som gjør tilsvarende). Hvordan output er formatert spiller ingen rolle. I denne sammenhengen har vi lite bruk for en pen regresjonstabell da $\beta$ ikke er av primær interesse.</span>
<span id="cb40-108"><a href="#cb40-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-109"><a href="#cb40-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-110"><a href="#cb40-110" aria-hidden="true" tabindex="-1"></a>Med andre ord kan voldsraten beskrives som:</span>
<span id="cb40-111"><a href="#cb40-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-114"><a href="#cb40-114" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-115"><a href="#cb40-115" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb40-116"><a href="#cb40-116" aria-hidden="true" tabindex="-1"></a><span class="co"># library(equatiomatic)</span></span>
<span id="cb40-117"><a href="#cb40-117" aria-hidden="true" tabindex="-1"></a><span class="co"># extract_eq(est, use_coefs = TRUE)</span></span>
<span id="cb40-118"><a href="#cb40-118" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-119"><a href="#cb40-119" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-120"><a href="#cb40-120" aria-hidden="true" tabindex="-1"></a>\operatorname{\widehat{voldskriminalitet}} = 0.51 + 0.41(\operatorname{prop<span class="sc">\_</span>unge<span class="sc">\_</span>menn})</span>
<span id="cb40-121"><a href="#cb40-121" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb40-122"><a href="#cb40-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-123"><a href="#cb40-123" aria-hidden="true" tabindex="-1"></a>Men vi har også sett at $r^2$ er ganske lav, bare <span class="in">`r round(summary(est)$r.squared, digits = 3)`</span>. Denne koeffisienten kalles også "coefficient of determination" og sier noe om i hvor stor grad modellen fanger opp variasjoenen i dataene. En lav $r^2$ betyr at modellen i liten grad gjør det. Vi må altså forvente at modellen vil bomme ganske kraftig i sine prediksjoner. Vi kan velge å ta modellen seriøst likevel, men ikke ha for store forventninger for prediksjonene!</span>
<span id="cb40-124"><a href="#cb40-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-125"><a href="#cb40-125" aria-hidden="true" tabindex="-1"></a>Et annet mål på hvor godt modellen treffer er "Root mean square error", RMSE. Dette kan skrives som:</span>
<span id="cb40-126"><a href="#cb40-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-127"><a href="#cb40-127" aria-hidden="true" tabindex="-1"></a>$$ rmse = \sqrt{ \frac{ \sum{(O_i-P_i)^2} }{N} }  $$</span>
<span id="cb40-128"><a href="#cb40-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-129"><a href="#cb40-129" aria-hidden="true" tabindex="-1"></a>der $O$ er de observerte verdiene og $P$ er de predikerte verdiene for observasjon $i$. Merk at $(O_i-P_i)$ er residualene. I R kan vi hente ut residualene fra regresjons-objektet med dollartegnet <span class="in">`...$res`</span> etter objektnavnet. Da kan du regne ut RMSE som følger:</span>
<span id="cb40-130"><a href="#cb40-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-133"><a href="#cb40-133" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-134"><a href="#cb40-134" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb40-135"><a href="#cb40-135" aria-hidden="true" tabindex="-1"></a>rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(est<span class="sc">$</span>res<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb40-136"><a href="#cb40-136" aria-hidden="true" tabindex="-1"></a>rmse</span>
<span id="cb40-137"><a href="#cb40-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-138"><a href="#cb40-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-139"><a href="#cb40-139" aria-hidden="true" tabindex="-1"></a>RMSE sier altså omtrentlig hvor mye modellen i gjennomsnitt bommer på de observerte verdiene. <span class="ot">[^linear_regresjon-2]</span>. Hvorvidt det er presist *nok* eller ikke vil vel strengt tatt komme an på behovet for presisjon, altså: hva man skal bruke det til.</span>
<span id="cb40-140"><a href="#cb40-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-141"><a href="#cb40-141" aria-hidden="true" tabindex="-1"></a><span class="ot">[^linear_regresjon-2]: </span>Denne formuleringen er ganske omtrentlig. RMSE er egentlig kvadratroten av gjennomsnittet til de kvadrerte residualene, som er noe litt annet enn gjennomsnittet av de absolutte verdiene av residualene. Det gir bl.a. litt mer vekt til store residualer enn et vanlig gjennomsnitt.</span>
<span id="cb40-142"><a href="#cb40-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-143"><a href="#cb40-143" aria-hidden="true" tabindex="-1"></a>For å få litt bedre tak på hva RMSE betyr kan vi se på et plot av de predikerte og observerte verdiene. Vi kan predikere vold for hver enkelt kommune basert på denne modellen, som altså er den forventede voldsraten *hvis modellen er sann*. Funksjonen <span class="in">`predict()`</span> gir oss hva vi trenger.</span>
<span id="cb40-144"><a href="#cb40-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-147"><a href="#cb40-147" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-148"><a href="#cb40-148" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb40-149"><a href="#cb40-149" aria-hidden="true" tabindex="-1"></a>kom <span class="ot">&lt;-</span> kommune_train <span class="sc">%&gt;%</span></span>
<span id="cb40-150"><a href="#cb40-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> <span class="fu">predict</span>(est))</span>
<span id="cb40-151"><a href="#cb40-151" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-152"><a href="#cb40-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-153"><a href="#cb40-153" aria-hidden="true" tabindex="-1"></a>Merk at koden her lagde en kopi av datasettet der vi har alle de opprinnelige variablene pluss en variabel med de predikerte verdiene. Vi kan nå sammenlignet prediksjonene med de observerte utfallene.</span>
<span id="cb40-154"><a href="#cb40-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-157"><a href="#cb40-157" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-158"><a href="#cb40-158" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb40-159"><a href="#cb40-159" aria-hidden="true" tabindex="-1"></a><span class="co">#| error: false</span></span>
<span id="cb40-160"><a href="#cb40-160" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb40-161"><a href="#cb40-161" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kom, <span class="fu">aes</span>(<span class="at">x =</span> voldskriminalitet, <span class="at">y =</span> pred)) <span class="sc">+</span></span>
<span id="cb40-162"><a href="#cb40-162" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb40-163"><a href="#cb40-163" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb40-164"><a href="#cb40-164" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-165"><a href="#cb40-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-166"><a href="#cb40-166" aria-hidden="true" tabindex="-1"></a>Hvis prediksjonen hadde vært perfekt ville disse punktene ligget på linja, noe den jo ikke gjør. Modellen bommer altså ganske mye.</span>
<span id="cb40-167"><a href="#cb40-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-168"><a href="#cb40-168" aria-hidden="true" tabindex="-1"></a>Hva hvis vi vil vite forventet voldsrate for en kommune for en gitt andel unge menn? Løsningen er å lage et nytt datasett med de verdiene vi er interessert i og så predikere for dette datasettet med å spesifisere <span class="in">`newdata = dt`</span>. Her er et eksempel der vi ønsker å vite voldsraten hvis andelen unge menn er 15%.</span>
<span id="cb40-169"><a href="#cb40-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-172"><a href="#cb40-172" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-173"><a href="#cb40-173" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb40-174"><a href="#cb40-174" aria-hidden="true" tabindex="-1"></a>dt <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">prop_unge_menn =</span> <span class="dv">15</span>)</span>
<span id="cb40-175"><a href="#cb40-175" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">predict</span>(est, <span class="at">newdata =</span> dt)</span>
<span id="cb40-176"><a href="#cb40-176" aria-hidden="true" tabindex="-1"></a>p</span>
<span id="cb40-177"><a href="#cb40-177" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-178"><a href="#cb40-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-179"><a href="#cb40-179" aria-hidden="true" tabindex="-1"></a>I følge modellen vil altså en kommune der 15% av populasjonen er unge menn ha en <span class="in">`r round(p, digits = 3)`</span> voldshendelser per 1000 innbyggere. Fra tradisjonell statistikk vet vi jo at det er usikkerhet knyttet til dette estimatet og vi kan også ta det med i beregningen her. Vanligvis vil man estimere med et *konfidensintervall*, som gjelder hvis man estimerer et gjennomsnitt i en gruppe. Her skal vi derimot predikere for en enkelt kommune, som da har større usikkerhet enn om man estimerer for en enkelt observasjon. Dette kalles prediksjonsintervall og må spesifiseres i koden. Hvis det ikke er gitt vil R gi konfidensintervallet.</span>
<span id="cb40-180"><a href="#cb40-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-183"><a href="#cb40-183" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-184"><a href="#cb40-184" aria-hidden="true" tabindex="-1"></a>p_ki <span class="ot">&lt;-</span> <span class="fu">predict</span>(est, <span class="at">newdata =</span> dt, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span>
<span id="cb40-185"><a href="#cb40-185" aria-hidden="true" tabindex="-1"></a>p_ki</span>
<span id="cb40-186"><a href="#cb40-186" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-187"><a href="#cb40-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-188"><a href="#cb40-188" aria-hidden="true" tabindex="-1"></a>Tolkningen er ellers tilsvarende som for konfidensintervall: vi forventer med "95% sannsynlighet"<span class="ot">[^linear_regresjon-3]</span> at voldsraten vil være mellom  <span class="in">`r round(p_ki[2], 1)`</span> og <span class="in">`r round(p_ki[3], 1)`</span> per 1000 innbyggere.</span>
<span id="cb40-189"><a href="#cb40-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-190"><a href="#cb40-190" aria-hidden="true" tabindex="-1"></a><span class="ot">[^linear_regresjon-3]: </span>Dette er en omtrentelig formulering. Alle sannsynligheter gjelder i det lange løp: altså hvis man gjør undersøkelsen veldig mange ganger.</span>
<span id="cb40-191"><a href="#cb40-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-192"><a href="#cb40-192" aria-hidden="true" tabindex="-1"></a><span class="fu">### Multippel regresjon</span></span>
<span id="cb40-193"><a href="#cb40-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-194"><a href="#cb40-194" aria-hidden="true" tabindex="-1"></a>Enkel regresjon er nettopp enkel og prediksjonen blir ikke så god. Men vi kan komplisere vesentlig ved å inkludere flere variable og bruke alle triksene man evt. har lært om multippel regresjon tidligere, primært interaksjonsledd, polynomer og transformasjoner osv. (Det er ok om du ikke har lært alt dette tidligere).</span>
<span id="cb40-195"><a href="#cb40-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-196"><a href="#cb40-196" aria-hidden="true" tabindex="-1"></a>I R vil vi da bare legge til flere variabelnavn i formelen. Ellers er det meste likt som for enkel lineær regresjon.</span>
<span id="cb40-197"><a href="#cb40-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-200"><a href="#cb40-200" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-201"><a href="#cb40-201" aria-hidden="true" tabindex="-1"></a>est_m <span class="ot">&lt;-</span> <span class="fu">lm</span>(voldskriminalitet <span class="sc">~</span> prop_unge_menn <span class="sc">+</span> inntekt_totalt_median <span class="sc">+</span> shj_unge <span class="sc">+</span></span>
<span id="cb40-202"><a href="#cb40-202" aria-hidden="true" tabindex="-1"></a>                   ant_husholdninger ,</span>
<span id="cb40-203"><a href="#cb40-203" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> kommune_train)</span>
<span id="cb40-204"><a href="#cb40-204" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(est_m)</span>
<span id="cb40-205"><a href="#cb40-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-206"><a href="#cb40-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-207"><a href="#cb40-207" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-208"><a href="#cb40-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-209"><a href="#cb40-209" aria-hidden="true" tabindex="-1"></a>Merk at $r^2$ nå har gått betraktelig opp, til ca <span class="in">`r round(summary(est_m)$r.squared, digits = 2)`</span>. Gitt at vi tolker dette som i hvor stor grad vi kan *predikere* utfallet fra datasettet, så er det kanskje likevel ikke imponerende høyt: vi vil fremdeles forvente mye feil prediksjon.</span>
<span id="cb40-210"><a href="#cb40-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-211"><a href="#cb40-211" aria-hidden="true" tabindex="-1"></a>Her er et scatterplot av observert mot forventet voldsrater:</span>
<span id="cb40-212"><a href="#cb40-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-215"><a href="#cb40-215" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-216"><a href="#cb40-216" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb40-217"><a href="#cb40-217" aria-hidden="true" tabindex="-1"></a><span class="co">#| error: false</span></span>
<span id="cb40-218"><a href="#cb40-218" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb40-219"><a href="#cb40-219" aria-hidden="true" tabindex="-1"></a>kom_pred <span class="ot">&lt;-</span> kommune_train <span class="sc">%&gt;%</span></span>
<span id="cb40-220"><a href="#cb40-220" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> <span class="fu">predict</span>(est_m))</span>
<span id="cb40-221"><a href="#cb40-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-222"><a href="#cb40-222" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kom_pred, <span class="fu">aes</span>(<span class="at">x =</span> voldskriminalitet, <span class="at">y =</span> pred)) <span class="sc">+</span></span>
<span id="cb40-223"><a href="#cb40-223" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb40-224"><a href="#cb40-224" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb40-225"><a href="#cb40-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-226"><a href="#cb40-226" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-227"><a href="#cb40-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-228"><a href="#cb40-228" aria-hidden="true" tabindex="-1"></a><span class="fu">### Sammenligning av modeller med ulik kompleksitet</span></span>
<span id="cb40-229"><a href="#cb40-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-230"><a href="#cb40-230" aria-hidden="true" tabindex="-1"></a>La oss nå systematisk sammenligne flere modeller med ulik kompleksitet. Vi lager først et datasett med utvalgte variable og bruker formelen <span class="in">`voldskriminalitet ~ .`</span> for å ta med alle variable.</span>
<span id="cb40-231"><a href="#cb40-231" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-234"><a href="#cb40-234" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-235"><a href="#cb40-235" aria-hidden="true" tabindex="-1"></a>kom_s <span class="ot">&lt;-</span> kommune_train <span class="sc">%&gt;%</span></span>
<span id="cb40-236"><a href="#cb40-236" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(kommune, kommune_nr, ordenslovbrudd,</span>
<span id="cb40-237"><a href="#cb40-237" aria-hidden="true" tabindex="-1"></a>            nark_alko_kriminalitet, trafikklovbrudd, andre_lovbrudd,</span>
<span id="cb40-238"><a href="#cb40-238" aria-hidden="true" tabindex="-1"></a>            prop_unge_menn))</span>
<span id="cb40-239"><a href="#cb40-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-240"><a href="#cb40-240" aria-hidden="true" tabindex="-1"></a>full_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(voldskriminalitet <span class="sc">~</span> . , <span class="at">data =</span> kom_s)</span>
<span id="cb40-241"><a href="#cb40-241" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(full_mod)</span>
<span id="cb40-242"><a href="#cb40-242" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-243"><a href="#cb40-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-244"><a href="#cb40-244" aria-hidden="true" tabindex="-1"></a>$r^2$ gikk noe opp, til <span class="in">`r round(summary(full_mod)$r.squared, digits = 3)`</span>.</span>
<span id="cb40-245"><a href="#cb40-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-246"><a href="#cb40-246" aria-hidden="true" tabindex="-1"></a><span class="fu">### Eksempel på overfitting</span></span>
<span id="cb40-247"><a href="#cb40-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-248"><a href="#cb40-248" aria-hidden="true" tabindex="-1"></a>Men vi kan gjøre modellen ekstra komplisert ved inkludere alle mulige interaksjonsledd. En åpenbar ulempe med dette er at hver enkelt koeffisent blir svært mye vanskeligere å tolke. Vi fokuserer derfor kun på $r^2$ og RMSE.</span>
<span id="cb40-249"><a href="#cb40-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-250"><a href="#cb40-250" aria-hidden="true" tabindex="-1"></a>Her bygger vi fire modeller med økende kompleksitet og sammenligner RMSE for training-data:</span>
<span id="cb40-251"><a href="#cb40-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-254"><a href="#cb40-254" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-255"><a href="#cb40-255" aria-hidden="true" tabindex="-1"></a>est1 <span class="ot">&lt;-</span> est     <span class="co"># enkel modell med bare prop_unge_menn (estimert over)</span></span>
<span id="cb40-256"><a href="#cb40-256" aria-hidden="true" tabindex="-1"></a>est2 <span class="ot">&lt;-</span> est_m   <span class="co"># multippel regresjon (estimert over)</span></span>
<span id="cb40-257"><a href="#cb40-257" aria-hidden="true" tabindex="-1"></a>est3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(voldskriminalitet <span class="sc">~</span> .<span class="sc">^</span><span class="dv">2</span>, <span class="at">data =</span> kom_s)    <span class="co"># alle 2-veis interaksjoner</span></span>
<span id="cb40-258"><a href="#cb40-258" aria-hidden="true" tabindex="-1"></a>est4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(voldskriminalitet <span class="sc">~</span> .<span class="sc">^</span><span class="dv">3</span>, <span class="at">data =</span> kom_s)    <span class="co"># alle 3-veis interaksjoner</span></span>
<span id="cb40-259"><a href="#cb40-259" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-260"><a href="#cb40-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-261"><a href="#cb40-261" aria-hidden="true" tabindex="-1"></a>RMSE for training-data:</span>
<span id="cb40-262"><a href="#cb40-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-265"><a href="#cb40-265" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-266"><a href="#cb40-266" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb40-267"><a href="#cb40-267" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(est1<span class="sc">$</span>res<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb40-268"><a href="#cb40-268" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(est2<span class="sc">$</span>res<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb40-269"><a href="#cb40-269" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(est3<span class="sc">$</span>res<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb40-270"><a href="#cb40-270" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">mean</span>(est4<span class="sc">$</span>res<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb40-271"><a href="#cb40-271" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-272"><a href="#cb40-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-273"><a href="#cb40-273" aria-hidden="true" tabindex="-1"></a>For training-data ser vi altså at RMSE synker for hver modell. Mer kompleksitet gir tilsynelatende bedre tilpassning. Men hva skjer med testing-data?</span>
<span id="cb40-274"><a href="#cb40-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-275"><a href="#cb40-275" aria-hidden="true" tabindex="-1"></a><span class="fu">### Predikere for nye data</span></span>
<span id="cb40-276"><a href="#cb40-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-277"><a href="#cb40-277" aria-hidden="true" tabindex="-1"></a>Nå har vi bare sett på hvordan prediksjonen fungerer på training-datasettet. Vi må sjekke med testing-datasettet. Det lagde vi i begynnelsen, så nå henter vi det frem. I <span class="in">`predict()`</span> må vi nå angi <span class="in">`newdata =`</span>. Vi predikerer fra alle fire modellene samtidig og regner ut RMSE for testing-data:</span>
<span id="cb40-278"><a href="#cb40-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-281"><a href="#cb40-281" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-282"><a href="#cb40-282" aria-hidden="true" tabindex="-1"></a><span class="co">#| code-fold: false</span></span>
<span id="cb40-283"><a href="#cb40-283" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb40-284"><a href="#cb40-284" aria-hidden="true" tabindex="-1"></a><span class="co">#| error: false</span></span>
<span id="cb40-285"><a href="#cb40-285" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb40-286"><a href="#cb40-286" aria-hidden="true" tabindex="-1"></a>kommune_test <span class="ot">&lt;-</span> kommune_test <span class="sc">%&gt;%</span></span>
<span id="cb40-287"><a href="#cb40-287" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop_unge_menn =</span> (menn_18_25 <span class="sc">+</span> menn_26_35)<span class="sc">/</span>bef_totalt<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb40-288"><a href="#cb40-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-289"><a href="#cb40-289" aria-hidden="true" tabindex="-1"></a>kommune_pred <span class="ot">&lt;-</span> kommune_test <span class="sc">%&gt;%</span></span>
<span id="cb40-290"><a href="#cb40-290" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred1 =</span> <span class="fu">predict</span>(est1, <span class="at">newdata =</span> .),</span>
<span id="cb40-291"><a href="#cb40-291" aria-hidden="true" tabindex="-1"></a>         <span class="at">pred2 =</span> <span class="fu">predict</span>(est2, <span class="at">newdata =</span> .),</span>
<span id="cb40-292"><a href="#cb40-292" aria-hidden="true" tabindex="-1"></a>         <span class="at">pred3 =</span> <span class="fu">predict</span>(est3, <span class="at">newdata =</span> .),</span>
<span id="cb40-293"><a href="#cb40-293" aria-hidden="true" tabindex="-1"></a>         <span class="at">pred4 =</span> <span class="fu">predict</span>(est4, <span class="at">newdata =</span> .))</span>
<span id="cb40-294"><a href="#cb40-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-295"><a href="#cb40-295" aria-hidden="true" tabindex="-1"></a>rmse_test <span class="ot">&lt;-</span> kommune_pred <span class="sc">%&gt;%</span></span>
<span id="cb40-296"><a href="#cb40-296" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">res1 =</span> pred1 <span class="sc">-</span> voldskriminalitet,</span>
<span id="cb40-297"><a href="#cb40-297" aria-hidden="true" tabindex="-1"></a>         <span class="at">res2 =</span> pred2 <span class="sc">-</span> voldskriminalitet,</span>
<span id="cb40-298"><a href="#cb40-298" aria-hidden="true" tabindex="-1"></a>         <span class="at">res3 =</span> pred3 <span class="sc">-</span> voldskriminalitet,</span>
<span id="cb40-299"><a href="#cb40-299" aria-hidden="true" tabindex="-1"></a>         <span class="at">res4 =</span> pred4 <span class="sc">-</span> voldskriminalitet) <span class="sc">%&gt;%</span></span>
<span id="cb40-300"><a href="#cb40-300" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">RMSE_enkel =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(res1<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb40-301"><a href="#cb40-301" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_multippel =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(res2<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb40-302"><a href="#cb40-302" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_2veis =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(res3<span class="sc">^</span><span class="dv">2</span>)),</span>
<span id="cb40-303"><a href="#cb40-303" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_3veis =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>(res4<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb40-304"><a href="#cb40-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-305"><a href="#cb40-305" aria-hidden="true" tabindex="-1"></a>rmse_test</span>
<span id="cb40-306"><a href="#cb40-306" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-307"><a href="#cb40-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-308"><a href="#cb40-308" aria-hidden="true" tabindex="-1"></a>Her ser vi at de mest kompliserte modellene gir *dårligere* prediksjon på nye data! La oss også plotte predikert mot observert for den mest kompliserte modellen:</span>
<span id="cb40-309"><a href="#cb40-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-312"><a href="#cb40-312" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-313"><a href="#cb40-313" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb40-314"><a href="#cb40-314" aria-hidden="true" tabindex="-1"></a><span class="co">#| error: false</span></span>
<span id="cb40-315"><a href="#cb40-315" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb40-316"><a href="#cb40-316" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kommune_pred, <span class="fu">aes</span>(<span class="at">x =</span> voldskriminalitet, <span class="at">y =</span> pred4)) <span class="sc">+</span></span>
<span id="cb40-317"><a href="#cb40-317" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb40-318"><a href="#cb40-318" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb40-319"><a href="#cb40-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-320"><a href="#cb40-320" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-321"><a href="#cb40-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-322"><a href="#cb40-322" aria-hidden="true" tabindex="-1"></a>Ser dette rart ut? Det er noen observasjoner som har predikert skyhøy voldsrate! Disse prediksjonene bommer voldsomt.</span>
<span id="cb40-323"><a href="#cb40-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-324"><a href="#cb40-324" aria-hidden="true" tabindex="-1"></a>Sammenlignet er den enklere multippelregresjonsmodellen vesentlig bedre på nye data:</span>
<span id="cb40-325"><a href="#cb40-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-328"><a href="#cb40-328" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-329"><a href="#cb40-329" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb40-330"><a href="#cb40-330" aria-hidden="true" tabindex="-1"></a><span class="co">#| error: false</span></span>
<span id="cb40-331"><a href="#cb40-331" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb40-332"><a href="#cb40-332" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kommune_pred, <span class="fu">aes</span>(<span class="at">x =</span> voldskriminalitet, <span class="at">y =</span> pred2)) <span class="sc">+</span></span>
<span id="cb40-333"><a href="#cb40-333" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb40-334"><a href="#cb40-334" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span>
<span id="cb40-335"><a href="#cb40-335" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-336"><a href="#cb40-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-337"><a href="#cb40-337" aria-hidden="true" tabindex="-1"></a>Dette er en ganske ekstrem variant av *overfitting*. Ved å formulere en veldig komplisert modell som passer veldig godt til training-dataene kan vi ende opp med en modell som passer veldig, veldig dårlig til nye data. Hvis man skulle utforme f.eks. politikktiltak på grunnlag av en slik prediksjon vil det kunne gå riktig så dårlig.</span>
<span id="cb40-338"><a href="#cb40-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-339"><a href="#cb40-339" aria-hidden="true" tabindex="-1"></a>Det er altså slik at en enklere modell kan passe til *nye* data langt bedre enn en veldig komplisert modell. Grunnen er overfitting: modellen fanger opp vel så mye tilfeldig støy som det underliggende mønsteret. Støyen vil jo være annerledes i de nye dataene.</span>
<span id="cb40-340"><a href="#cb40-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-341"><a href="#cb40-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-342"><a href="#cb40-342" aria-hidden="true" tabindex="-1"></a><span class="fu">### Generalized additive models (GAM)</span></span>
<span id="cb40-343"><a href="#cb40-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-344"><a href="#cb40-344" aria-hidden="true" tabindex="-1"></a>Generaliserte additive modeller er i utgangspunktet som lineær regresjon, men inkluderer en eller flere *smoothing*-parametre. Disse smoothing-parametrene "lærer" funksjonsformen fra dataene i stedet for å anta en lineær sammenheng. Funksjonen <span class="in">`gam()`</span> fra pakken <span class="in">`mgcv`</span> brukes for dette, og <span class="in">`s()`</span> rundt en variabel angir at den skal ha en fleksibel form.</span>
<span id="cb40-345"><a href="#cb40-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-346"><a href="#cb40-346" aria-hidden="true" tabindex="-1"></a>Her er et eksempel der vi bruker GAM med noen utvalgte variable:</span>
<span id="cb40-347"><a href="#cb40-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-350"><a href="#cb40-350" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-351"><a href="#cb40-351" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb40-352"><a href="#cb40-352" aria-hidden="true" tabindex="-1"></a><span class="co">#| error: false</span></span>
<span id="cb40-353"><a href="#cb40-353" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb40-354"><a href="#cb40-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-355"><a href="#cb40-355" aria-hidden="true" tabindex="-1"></a>gam_mod <span class="ot">&lt;-</span> <span class="fu">gam</span>(voldskriminalitet <span class="sc">~</span> <span class="fu">s</span>(prop_unge_menn) <span class="sc">+</span> <span class="fu">s</span>(inntekt_totalt_median) <span class="sc">+</span> <span class="fu">s</span>(shj_unge),</span>
<span id="cb40-356"><a href="#cb40-356" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> kommune_train)</span>
<span id="cb40-357"><a href="#cb40-357" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gam_mod)</span>
<span id="cb40-358"><a href="#cb40-358" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-359"><a href="#cb40-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-360"><a href="#cb40-360" aria-hidden="true" tabindex="-1"></a>Vi kan plotte de estimerte smoothing-funksjonene for å se hvordan sammenhengen ser ut:</span>
<span id="cb40-361"><a href="#cb40-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-364"><a href="#cb40-364" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb40-365"><a href="#cb40-365" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb40-366"><a href="#cb40-366" aria-hidden="true" tabindex="-1"></a><span class="co">#| error: false</span></span>
<span id="cb40-367"><a href="#cb40-367" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb40-368"><a href="#cb40-368" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gam_mod)</span>
<span id="cb40-369"><a href="#cb40-369" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb40-370"><a href="#cb40-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-371"><a href="#cb40-371" aria-hidden="true" tabindex="-1"></a>Merk at <span class="in">`s()`</span> tilpasser en fleksibel kurve til dataene. Fordelen med GAM er at vi ikke trenger å anta en lineær sammenheng. Ulempen er at det er vanskeligere å tolke koeffisientene direkte, men for *prediksjon* er dette ofte ikke et problem.</span>
<span id="cb40-372"><a href="#cb40-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-373"><a href="#cb40-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-374"><a href="#cb40-374" aria-hidden="true" tabindex="-1"></a><span class="fu">### Oppsummerende kommentar</span></span>
<span id="cb40-375"><a href="#cb40-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-376"><a href="#cb40-376" aria-hidden="true" tabindex="-1"></a>Dette gjelder generelt: mer komplisert regresjonsmodell vil gi tilsynelatende bedre tilpassning til data enten man måler med $r^2$ eller RMSE. Man kan riktignok bruke mål på tilpassning som justerer for antall parametre etc (f.eks. justert $r^2$, AIC eller BIC), som kanskje kan bedre dette noe, men det vil ofte lede til overfitting likevel.</span>
<span id="cb40-377"><a href="#cb40-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-378"><a href="#cb40-378" aria-hidden="true" tabindex="-1"></a>Det er derfor veldig viktig å teste modellen mot *nye* data. I praksis testing-dataene man lagde til å begynne med.</span>
<span id="cb40-379"><a href="#cb40-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-380"><a href="#cb40-380" aria-hidden="true" tabindex="-1"></a>I resten av kurset skal vi unngå å bruke latterlige kompliserte modeller som ble demonstrert ovenfor. Man kan godt bruke interaksjonsledd, polynomer, splines og andre fancy ting. Men med måte.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>